package com.spring.security.controller;

import com.spring.security.payload.UserRequest;
import com.spring.security.payload.UserResponse;
import com.spring.security.util.JwtUtil;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.web.bind.annotation.*;

import java.security.Principal;

@RestController
@RequestMapping("/user")
public class LoginController {

    @Autowired
    private JwtUtil util;

    @Autowired
    private AuthenticationManager authenticationManager;

    // User login to get JWT
    @PostMapping("/login")
    public ResponseEntity<UserResponse> loginUser(@RequestBody UserRequest userRequest) {

        System.out.println("Login end point  ");
        // validate the user by using authentication manager
        Authentication auth = authenticationManager.authenticate(
                new UsernamePasswordAuthenticationToken(userRequest.getUsername(), userRequest.getPassword()));

        SecurityContextHolder.getContext().setAuthentication(auth);

        // Generate the token by using JwtUtil
        String token = util.generateToken(userRequest.getUsername());
        System.out.println("Token information :: " + token);

        return ResponseEntity.ok(new UserResponse(token, "Generated by the user: "+userRequest.getUsername()));
    }

    // Testing after successful login
    @GetMapping("/welcome")
    public ResponseEntity<String> showUserData(Principal p) {
        System.out.println(p.getClass().getName());
        return ResponseEntity.ok("Hello: " + p.getName());
    }
}
